# Generated by Django 5.2.4 on 2025-07-20 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Genre name (e.g., Action, Comedy, Drama)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the genre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('description', models.TextField(help_text='Video description')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='video_thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='External thumbnail URL (used if no image file uploaded)', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Video duration', null=True)),
                ('age_rating', models.CharField(choices=[('FSK 0', 'FSK 0'), ('FSK 6', 'FSK 6'), ('FSK 12', 'FSK 12'), ('FSK 16', 'FSK 16'), ('FSK 18', 'FSK 18')], default='FSK 16', help_text='Age rating classification', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this video should be featured on homepage')),
                ('genre', models.ForeignKey(help_text='Video genre', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.genre')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('120p', '120p'), ('360p', '360p'), ('720p', '720p'), ('1080p', '1080p')], help_text='Video quality', max_length=10)),
                ('file', models.FileField(help_text='Video file', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])])),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the video has been processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video File',
                'verbose_name_plural': 'Video Files',
                'unique_together': {('video', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_seconds', models.PositiveIntegerField(default=0, help_text='Progress in seconds')),
                ('last_resolution', models.CharField(choices=[('120p', '120p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='720p', help_text='Last used video resolution', max_length=10)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the video has been completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='videos.video')),
            ],
            options={
                'verbose_name': 'Watch Progress',
                'verbose_name_plural': 'Watch Progress',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
