# Generated by Django 5.2.4 on 2025-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External thumbnail URL (used if no image file uploaded)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='video_thumbnails/'),
        ),
    ]
