# Generated by Django 5.2.4 on 2025-07-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_thumbnail_url_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age_rating',
            field=models.CharField(choices=[('FSK 0', 'FSK 0'), ('FSK 6', 'FSK 6'), ('FSK 12', 'FSK 12'), ('FSK 16', 'FSK 16'), ('FSK 18', 'FSK 18')], default='FSK 16', help_text='Age rating classification', max_length=10),
        ),
    ]
