# Generated by Django 5.2.4 on 2025-07-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprogress',
            name='last_resolution',
            field=models.CharField(choices=[('120p', '120p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='720p', help_text='Last used video resolution', max_length=10),
        ),
    ]
