# Generated by Django 5.2.4 on 2025-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_watchprogress_last_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Video duration', null=True),
        ),
    ]
